/** The endpoints both frontends call, listed on the Integration page. */
export const API_REFERENCE: { method: string; path: string; description: string; direction: 'inbound' | 'outbound' }[] = [
  { method: 'MQTT', path: 'spp/{mac}/sensor/{status_change|value_change}/{key}', description: 'AKCP units publish readings and status codes to the broker; the API holds one subscription for the fleet.', direction: 'inbound' },
  { method: 'POST', path: '/auth/admin/login', description: 'Admin sign-in with a password; the token carries the distribution center.', direction: 'outbound' },
  { method: 'POST', path: '/auth/token/login', description: 'Employee and technician sign-in with the registration token their admin issued.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}', description: 'The distribution center and its outlet count.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/outlets', description: 'Master data: outlets, with create, update and delete.', direction: 'outbound' },
  { method: 'GET', path: '/device-types', description: 'AKCP models, their ports and built-in sensors.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/devices', description: 'Registered units; a device answers with its sensors and port map.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/sensors', description: 'Every sensor in one call, which is what the floor plans draw.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/employees', description: 'Accounts, plus approve, issue token and revoke.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/technicians', description: 'Maintenance technicians and their app tokens.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/contact-persons', description: 'Outlet contacts and the channels they are reached on.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/alerts', description: 'Alert list, filtered by outlet, status, category and date.', direction: 'outbound' },
  { method: 'POST', path: '/alerts/{id}/respond', description: 'Employee field response with notes and photo proof; the first responder claims it.', direction: 'outbound' },
  { method: 'POST', path: '/alerts/{id}/status', description: 'Lifecycle move: acknowledge, start responding, resolve, verify.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/tickets', description: 'Maintenance work list, with create and patch.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/readings', description: 'Sensor time series, raw or averaged into buckets.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/stats', description: 'Dashboard and analysis aggregates computed in the database.', direction: 'outbound' },
  { method: 'GET', path: '/distributors/{id}/integration', description: 'Channel settings, request log, unmatched events and the channel tests.', direction: 'outbound' },
  { method: 'POST', path: '/uploads', description: 'Photo proof for an alert response or a finished ticket.', direction: 'outbound' },
];
